services:

  postgres:
    image: postgres:17 # NOTE: Don't even think about using the latest tag
    ports:
      - "5432:5432"
    container_name: nateqk_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nateqk
    restart: unless-stopped
    volumes:
      - ./bot/app.toml:/src/bot/app.toml
