services:

  postgres:
    image: postgres:17
    network_mode: "host"
    container_name: nateqk_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
